### PR TITLE
NL HVAC Metrics rework

### PR DESCRIPTION
**Pull request by mjkapkan**
Added majority of Nissan Leaf HVAC metrics and aligned for different model year cars. Tested on NL 2013 and 2016 versions.

### CODE REVIEW

**Comment by dexterbg** [comment]
Please resolve two issues with this pull request:
1. A modified version of the webserver's compressed charts javascript is included, but no corresponding source change. If the source hasn't changed, there must be no change to the compiled file. It's also not clear how this change relates to the other changes. Please either include the source change or exclude the compressed file.
2. The leaf documentation index file has a merge conflct against the current master. Please resolve conflicts before submitting a pull request.

**Comment by mjkapkan** [comment]
> Please resolve two issues with this pull request:
> 
> 1. A modified version of the webserver's compressed charts javascript is included, but no corresponding source change. If the source hasn't changed, there must be no change to the compiled file. It's also not clear how this change relates to the other changes. Please either include the source change or exclude the compressed file.
> 2. The leaf documentation index file has a merge conflct against the current master. Please resolve conflicts before submitting a pull request.

1. The index.rst in the main dir was edited unintentionally, same goes for the chats.js.gz file, So i just copied them from the main repo and made another commit (it took a few tries as this is my first pull request ever). 
2. Seems like someone changed the documentation in the mean time, so I will reveiw and resolve those conflicts this week.

**Comment by mjkapkan** [comment]
@dexterbg Should be good now.

**Comment by dexterbg** [comment]
Perfect, thanks :)

**Comment by dalathegreat** [comment]
Very nice! 👍

**Pull request merged**
