### PR TITLE
Wifi: default to 20Mhz bandwidth

### PR DESCRIPTION
**Pull request by drc38**
@dexterbg meant for this to go into the master as well but wasn't sure how new PR's were working across v3.3 and master, cheers Derek

### CODE REVIEW

**Comment by dexterbg** [comment]
Derek, did you test this? My master build crashes on boot with this change.

```
D (3844) events: Signal(network.interface.change)
D (3844) events: Signal(system.event)
D (3854) events: Signal(system.wifi.ap.stop)
I (3854) netmanager: WIFI access point is down
I (3854) esp32wifi: AP stopped
D (3854) events: Signal(system.event)
D (3854) events: Signal(system.wifi.ap.start)
I (3854) netmanager: WIFI access point is up
I (3984) script: Duktape: Initialising module system
D (4004) script: Duktape: Pre-Registered function assert
D (4004) script: Duktape: Pre-Registered function print
D (4004) script: Duktape: Pre-Registered object HTTP
D (4004) script: Duktape: Pre-Registered object HTTP function Request
D (4014) script: Duktape: Pre-Registered object HTTP function request
D (4024) script: Duktape: Pre-Registered object OvmsCommand
D (4024) script: Duktape: Pre-Registered object OvmsCommand function Exec
D (4034) script: Duktape: Pre-Registered object OvmsCommand function Register
D (4034) script: Duktape: Pre-Registered object OvmsConfig
D (4044) script: Duktape: Pre-Registered object OvmsConfig function Delete
D (4054) script: Duktape: Pre-Registered object OvmsConfig function Get
D (4054) script: Duktape: Pre-Registered object OvmsConfig function GetValues
D (4064) script: Duktape: Pre-Registered object OvmsConfig function Instances
D (4074) script: Duktape: Pre-Registered object OvmsConfig function Params
D (4074) script: Duktape: Pre-Registered object OvmsConfig function Set
D (4084) script: Duktape: Pre-Registered object OvmsConfig function SetValues
D (4094) script: Duktape: Pre-Registered object OvmsEvents
D (4094) script: Duktape: Pre-Registered object OvmsEvents function RaiseGuru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled.
Core 1 register dump:
PC      : 0x401084f9  PS      : 0x00060430  A0      : 0x80109d0f  A1      : 0x3ffc3000  
A2      : 0x3f8445c8  A3      : 0x40158648  A4      : 0x00000000  A5      : 0x00000000  
A6      : 0x3ffc31b0  A7      : 0x00000000  A8      : 0x00000000  A9      : 0x3ffc2fd0  
A10     : 0x3f8445c8  A11     : 0x40158648  A12     : 0x3f8445c8  A13     : 0x00000000  
A14     : 0x00000000  A15     : 0x3f826de8  SAR     : 0x0000001c  EXCCAUSE: 0x0000001c  
EXCVADDR: 0x00000030  LBEG    : 0x400029ac  LEND    : 0x400029cb  LCOUNT  : 0x00000000  

ELF file SHA256: 3ff76e6c6899da47

Backtrace: 0x401084f9:0x3ffc3000 0x40109d0c:0x3ffc3030 0x401598b5:0x3ffc3170 0x40156b3a:0x3ffc31e0 0x400f9e92:0x3ffc3220 0x400fa055:0x3ffc3250 0x400fa13c:0x3ffc32b0 0x400fa1c1:0x3ffc32f0

Rebooting...
```

The backtrace decodes to:
```
Using elf file: /home/balzer/esp/Open-Vehicle-Monitoring-System-3/vehicle/OVMS.V3/build/ovms3.elf
0x401084f9 is in mg_create_connection (/home/balzer/esp/Open-Vehicle-Monitoring-System-3/vehicle/OVMS.V3/components/mongoose/mongoose/mongoose.c:2640).
2635	MG_INTERNAL struct mg_connection *mg_create_connection(
2636	    struct mg_mgr *mgr, mg_event_handler_t callback,
2637	    struct mg_add_sock_opts opts) {
2638	  struct mg_connection *conn = mg_create_connection_base(mgr, callback, opts);
2639	
2640	  if (conn != NULL && !conn->iface->vtable->create_conn(conn)) {
2641	    MG_FREE(conn);
2642	    conn = NULL;
2643	  }
2644	  if (conn == NULL) {
0x40109d0c is in mg_bind_opt (/home/balzer/esp/Open-Vehicle-Monitoring-System-3/vehicle/OVMS.V3/components/mongoose/mongoose/mongoose.c:3141).
3136	  if (mg_parse_address(address, &sa, &proto, host, sizeof(host)) <= 0) {
3137	    MG_SET_PTRPTR(opts.error_string, "cannot parse address");
3138	    return NULL;
3139	  }
3140	
3141	  nc = mg_create_connection(mgr, callback, add_sock_opts);
3142	  if (nc == NULL) {
3143	    return NULL;
3144	  }
3145	
0x401598b5 is in OvmsWebServer::NetManInit(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, void*) (/home/balzer/esp/Open-Vehicle-Monitoring-System-3/vehicle/OVMS.V3/components/ovms_webserver/src/ovms_webserver.cpp:161).
156	
157	  char *error_string;
158	  struct mg_bind_opts bind_opts = {};
159	  memset(&bind_opts, 0, sizeof(bind_opts));
160	  bind_opts.error_string = (const char**) &error_string;
161	  struct mg_connection *nc = mg_bind_opt(mgr, ":80", EventHandler, bind_opts);
162	  if (!nc)
163	    ESP_LOGE(TAG, "Cannot bind to port 80: %s", error_string);
164	  else {
165	    mg_set_protocol_http_websocket(nc);
0x40156b3a is in std::_Function_handler<void (std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, void*), std::_Bind<std::_Mem_fn<void (OvmsWebServer::*)(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, void*)> (OvmsWebServer*, std::_Placeholder<1>, std::_Placeholder<2>)> >::_M_invoke(std::_Any_data const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&, void*&&) (/home/balzer/esp/xtensa-esp32-elf-1.22.0-97/xtensa-esp32-elf/include/c++/5.2.0/functional:600).
595	      template<typename... _Args, typename _Req
596	               = _Require<typename _Traits::__lvalue,
597	                          _CheckArgs<_Pack<_Args...>>>>
598		result_type
599		operator()(_Class* __object, _Args&&... __args) const
600		{ return (__object->*_M_pmf)(std::forward<_Args>(__args)...); }
601	
602	      // Handle smart pointers, references and pointers to derived
603	      template<typename _Tp, typename... _Args, typename _Req
604	               = _Require<_NotSame<_Class, _Tp>, _NotSame<_Class*, _Tp>,
0x400f9e92 is in std::function<void (std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, void*)>::operator()(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, void*) const (/home/balzer/esp/xtensa-esp32-elf-1.22.0-97/xtensa-esp32-elf/include/c++/5.2.0/functional:2271).
2266	    function<_Res(_ArgTypes...)>::
2267	    operator()(_ArgTypes... __args) const
2268	    {
2269	      if (_M_empty())
2270		__throw_bad_function_call();
2271	      return _M_invoker(_M_functor, std::forward<_ArgTypes>(__args)...);
2272	    }
2273	
2274	#if __cpp_rtti
2275	  template<typename _Res, typename... _ArgTypes>
0x400fa055 is in OvmsEvents::HandleQueueSignalEvent(event_queue_t*) (/home/balzer/esp/Open-Vehicle-Monitoring-System-3/vehicle/OVMS.V3/main/ovms_events.cpp:261).
256	      {
257	      for (EventCallbackList::iterator itc=el->begin(); itc!=el->end(); ++itc)
258	        {
259	        m_current_started = monotonictime;
260	        m_current_callback = *itc;
261	        m_current_callback->m_callback(m_current_event, msg->body.signal.data);
262	        m_current_callback = NULL;
263	        }
264	      }
265	    }
0x400fa13c is in OvmsEvents::EventTask() (/home/balzer/esp/Open-Vehicle-Monitoring-System-3/vehicle/OVMS.V3/main/ovms_events.cpp:215).
210	        {
211	        case EVENT_none:
212	          break;
213	        case EVENT_signal:
214	          m_current_event = msg.body.signal.event;
215	          HandleQueueSignalEvent(&msg);
216	          esp_task_wdt_reset(); // Reset WATCHDOG timer for this task
217	          m_current_event.clear();
218	          break;
219	        default:
0x400fa1c1 is in EventLaunchTask(void*) (/home/balzer/esp/Open-Vehicle-Monitoring-System-3/vehicle/OVMS.V3/main/ovms_events.cpp:80).
75	
76	void EventLaunchTask(void *pvParameters)
77	  {
78	  OvmsEvents* me = (OvmsEvents*)pvParameters;
79	
80	  me->EventTask();
81	  }
82	
83	void event_trace(int verbosity, OvmsWriter* writer, OvmsCommand* cmd, int argc, const char* const* argv)
84	  {
```

Commenting out just the `esp_wifi_set_bandwidth()` calls avoids the crash.

I'm going to revert the commit now.

Regards,
Michael

**Comment by drc38** [comment]
Thanks for letting me know,  I have been testing it for over a week now. Both with and without setting the new parameter to set the bandwidth. 

If the call to change bandwidth hasn't worked it should just error out and not cause a crash.

Can you spot anything in the code that might be causing an issue?

**Comment by drc38** [comment]
Perhaps where the function is called is causing a race condition? It's odd that I haven't had the same issue.

**Comment by drc38** [comment]
I've tried a range of wifi options and modes to try and force a similar error on my unit but cannot replicate it. Looking at the esp-idf docs on fatal errors it says in relation to guru meditation errors:
 _LoadProhibited, StoreProhibited
This CPU exception happens when application attempts to read from or write to an invalid memory location. The address which was written/read is found in EXCVADDR register in the register dump. If this address is zero, it usually means that application attempted to dereference a NULL pointer. If this address is close to zero, it usually means that application attempted to access member of a structure, but the pointer to the structure was NULL. If this address is something else (garbage value, not in 0x3fxxxxxx - 0x6xxxxxxx range), it likely means that the pointer used to access the data was either not initialized or was corrupted._

Is the extra code/call in your build possibly running it into a memory limitation?

**Comment by dexterbg** [comment]
No. I'd assume the `esp_wifi_set_bandwidth()` call doesn't verify the interface pointer and try inserting a check for that in our code.

**Comment by dexterbg** [comment]
I'll try that this evening.

**Comment by drc38** [comment]
As the 'SetAPWifiBW();` function is called after `esp_wifi_get_mac(ESP_IF_WIFI_AP, m_mac_ap);` `ESP_IF_WIFI_AP` should be defined but I guess it could still be Null.

**Comment by dexterbg** [comment]
Fixed. Apparently you cannot change the bandwidth on the fly, the wifi blob needs to restart the interfaces. The issue then arises from `esp_wifi_set_bandwidth()` recreating the wifi interfaces while the asynchronous event framework still processes the first wifi activation. So while the system relies on the interfaces being usable, firing up mongoose etc., the wifi blob kills them.

The solution is to move the bandwidth initialization to the actual mode initialization. Was there a reason not to do so in the first place? I've also added the current bandwidth & channel info to the `wifi status` command to verify the bandwidth is configured as desired.

Regards,
Michael

**Comment by drc38** [comment]
Great, thanks for investigating and figuring out what was going on. I'd considered where to call the change but thought using the event trigger would guarantee the AP was started/ready (ironically to prevent no interface being ready) looks like that was misguided. I'm guessing because I'm only using wifi (no modem) the async approach didn't cause issues on my setup.

**Pull request merged**
