### PR TITLE
Bolt EV: Initial work on the Bolt EV

### PR DESCRIPTION
**Pull request by kallisti5**
* Based on the original Volt / Ampera code

### CODE REVIEW

**Comment by dexterbg** [comment]
Alex,

nice!

Looks mostly good to me, but you need to change the "xva" namespace, as that is already allocated to Volt/Ampera.

The current naming scheme here would be "xcb" (for Chevrolet Bolt). Take care to change this everywhere "xva" is used in your code, e.g. also on web page paths.

The vehicle type also isn't correct. It should be something along the scheme defined in the developer guide i.e. include a manufacturer prefix, e.g. "CBOLT".

The vehicle type metric also still uses the "VA" prefix. It should always begin with the fixed vehicle type code, you may add model indicators after that.

Adding a line to the main README is good, but adding a brief note to the `changes.txt` file is mandatory.

Side note: it would really make my life easier if you could switch your whitespace scheme from tabs to spaces here. Reading partially tab indented code in web diffs is a PITA (see PR page "Files changed").

Regards,
Michael

**Comment by kallisti5** [comment]
Output with vehicle powered on:
```
m.egpio.input                            0,1,2,3,4,5,6,7,8,9
m.egpio.monitor
m.egpio.output                           4,5,6,7,8,9
m.freeram                                3521072
m.hardware                               OVMS WIFI BLE BT cores=2 rev=ESP32/3
m.monotonic                              66Sec
...
m.net.provider                           discordia
m.net.sq                                 -65dBm
m.net.type                               wifi
m.net.wifi.network                       discordia
m.net.wifi.sq                            -64.5dBm
m.serial
m.tasks                                  17
m.time.utc                               1643144628Sec
m.version                                3.3.001-116-gd9b6d9ee-dirty/ota_1/edge (build idf v3.3.4-848-g1ff5e24b1 Jan 25 2022 11:34:35)
s.v2.connected                           yes
s.v2.peers                               0
s.v3.connected
s.v3.peers
v.b.12v.current
v.b.12v.voltage                          12.86V
v.b.12v.voltage.alert
v.b.12v.voltage.ref                      12.6V
v.b.c.temp
v.b.c.temp.alert
v.b.c.temp.dev.max
v.b.c.temp.max
v.b.c.temp.min
v.b.c.voltage
v.b.c.voltage.alert
v.b.c.voltage.dev.max
v.b.c.voltage.max
v.b.c.voltage.min
v.b.cac
v.b.consumption                          0Wh/km
v.b.coulomb.recd
v.b.coulomb.recd.total
v.b.coulomb.used
v.b.coulomb.used.total
v.b.current
v.b.energy.recd
v.b.energy.recd.total
v.b.energy.used
v.b.energy.used.total
v.b.health
v.b.p.level.avg
v.b.p.level.max
v.b.p.level.min
v.b.p.level.stddev
v.b.p.temp.avg
v.b.p.temp.max
v.b.p.temp.min
v.b.p.temp.stddev
v.b.p.temp.stddev.max                    0°C
v.b.p.voltage.avg
v.b.p.voltage.grad
v.b.p.voltage.max
v.b.p.voltage.min
v.b.p.voltage.stddev
v.b.p.voltage.stddev.max                 0V
v.b.power
v.b.range.est
v.b.range.full
v.b.range.ideal                          324km
v.b.range.speed
v.b.soc                                  78%
v.b.soh
v.b.temp                                 15°C
v.b.voltage                              377V
v.c.12v.current
v.c.12v.power
v.c.12v.temp
v.c.12v.voltage
v.c.charging                             yes
v.c.climit                               16A
v.c.current                              31A
v.c.duration.full
v.c.duration.range
v.c.duration.soc
v.c.efficiency
v.c.kwh
v.c.kwh.grid
v.c.kwh.grid.total
v.c.limit.range
v.c.limit.soc
v.c.mode                                 standard
v.c.pilot                                yes
v.c.power
v.c.state                                charging
v.c.substate                             onrequest
v.c.temp
v.c.time                                 56Sec
v.c.timermode
v.c.timerstart
v.c.type
v.c.voltage                              246V
v.d.cp                                   yes
v.d.fl
v.d.fr
v.d.hood
v.d.rl
v.d.rr
v.d.trunk
v.e.alarm
v.e.aux12v
v.e.awake                                yes
v.e.c.config
v.e.c.login
v.e.cabinfan
v.e.cabinintake
v.e.cabinsetpoint
v.e.cabintemp
v.e.cabinvent
v.e.charging12v                          yes
v.e.cooling
v.e.drivemode
v.e.drivetime                            64Sec
v.e.footbrake                            0%
v.e.gear                                 -2
v.e.handbrake
v.e.headlights
v.e.heating
v.e.hvac
v.e.locked
v.e.on                                   yes
v.e.parktime                             0Sec
v.e.regenbrake
v.e.serv.range
v.e.serv.time
v.e.temp                                 9°C
v.e.throttle                             0%
v.e.valet
v.g.climit
v.g.current
v.g.duration.empty
v.g.duration.range
v.g.duration.soc
v.g.efficiency
v.g.generating
v.g.kwh
v.g.kwh.grid
v.g.kwh.grid.total
v.g.limit.range
v.g.limit.soc
v.g.mode
v.g.pilot
v.g.power
v.g.state
v.g.substate
v.g.temp
v.g.time                                 0Sec
v.g.timermode
v.g.timerstart
v.g.type
v.g.voltage
v.i.efficiency
v.i.power
v.i.temp                                 21°C
v.m.rpm                                  0
v.m.temp
v.p.acceleration
v.p.altitude
v.p.direction
v.p.gpshdop
v.p.gpslock
v.p.gpsmode
v.p.gpsspeed
v.p.latitude
v.p.location
v.p.longitude
v.p.odometer                             43329km
v.p.satcount
v.p.speed                                0km/h
v.p.trip
v.t.alert
v.t.health
v.t.pressure
v.t.temp
v.type                                   VAV20
v.vin                                    1G1FZXXXXXXXXXX
xva.v.ac.active                          no
xva.v.ac.front_blower_fan_speed          0%
xva.v.ac.preheat                         0
xva.v.ac.preheat_timer                   0
xva.v.b.charging_limits                  12,8
xva.v.e.coolant_heater_pwr
xva.v.e.coolant_temp                     0°C
xva.v.e.fuel
xva.v.p.trip.ev
```


Issues of note:

* BMS / Cell voltages empty?

v.b.c.voltage
v.b.c.voltage.alert
v.b.c.voltage.dev.max
v.b.c.voltage.max
v.b.c.voltage.min

OVMS#  bms status
No BMS status data available

**Comment by kallisti5** [comment]
> Looks mostly good to me, but you need to change the "xva" namespace, as that is already allocated to Volt/Ampera.
>
> The current naming scheme here would be "xcb" (for Chevrolet Bolt). Take care to change this everywhere "xva" is used in your code, e.g. also on web page paths.

Oops. done.  I really didn't understand the meaning of xva. Thanks!

> The vehicle type also isn't correct. It should be something along the scheme defined in the developer guide i.e. include a manufacturer prefix, e.g. "CBOLT".

Done.   I was a bit confused because the Volt/Ampera doesn't include the manufacturer name while everything else does.

I thought about including Ampera-e in the name, but the population of Ampera-e vehicles is pretty small and it was discontinued.  I also don't have access to one to test :-)

> The vehicle type metric also still uses the "VA" prefix. It should always begin with the fixed vehicle type code, you may add model indicators after that.

I honestly really didn't understand the m_type stuff and couldn't find any documentation on it.  Do you have anything to link to?

> Adding a line to the main README is good, but adding a brief note to the changes.txt file is mandatory.

Done

> Side note: it would really make my life easier if you could switch your whitespace scheme from tabs to spaces here. Reading partially tab indented code in web diffs is a PITA (see PR page "Files changed").

oof. I noticed a *LOT* of misaligned space indention in the Volt / Ampera code.   (three space indention, two space indention, 5 space indention, etc).

I'm personally a k&r indentation guy, but definitely want to maintain the correct style.. what are the intended style guidelines?
I do see that rogue tab in my changes and went ahead and removed it.

**Comment by dexterbg** [comment]
Alex,

the Volt/Ampera is an ancient module, dating back to before we needed a name space scheme, but as we follow the goal to avoid breaking compatibility for minor reasons, we don't change the established vehicle type codes.

On `v.type` / `m_type`: sorry, no real documentation on this. We've got a general vehicle type code defined by the implementation which tells the base type of the current vehicle, and a metric to be able to add variant info of the current vehicle if necessary. A client needing to know the vehicle type & model can query `v.type` to get both. The metric is set by the vehicle factory on instantiation, and may be modified by a vehicle later on to include a model suffix.

`m_type` is used by the Volt/Ampera module to add the model year to the metric. In your current code, you still assemble `m_type` (and thus set the metric) with the "VA" prefix, so that still needs to be changed.

On the `xva` → `xcb` rework: you missed the `va_ac_preheat` module.

A new issue with the current PR: you included a change to the webserver's `charts.js.gz` file (probably accidentally), please remove that from the PR.

Regards,
Michael

**Comment by dexterbg** [comment]
On whitespace & indentation etc.: you're free to use your personal preference in your module(s). When working on existing modules you shall keep the style used there.

I recommend using **astyle** (http://astyle.sourceforge.net/astyle.html) to easily reformat your modules, it's got a standard K&R template. It's a good idea to include the astyle configuration in your src tree, as we did on the VW e-Up:
- https://github.com/openvehicles/Open-Vehicle-Monitoring-System-3/blob/master/vehicle/OVMS.V3/components/vehicle_vweup/src/.astylerc

Best to do the reformatting now, so the initial commit is a clean diff reference.

**Comment by kallisti5** [comment]
reformatted K&R, dropped accidental charts.js.gz change..  still need to work on m/v_type

**Comment by Edwintenhaaf** [comment]
Hello Alex,

Many thanks for building the bolt ev support.
It works on my european Bolt named (Opel) Ampera-e.
Maybe that couldto be added to the description ?
I'm driving a 2017 Opel Amper-e with a 60kw battery.
As you might now the battery of all Bolts and Ampera-e will be replaced due to fire risk.
The new battery will be 66kw so I think there is a need for a checkbox 'I have a new battery pack' 
If I can help testing new builds let me know.

In the App I noticed that 'Charged'. showed me a value of 120.0kWh 
Don't know if this is because I upgraded firmware during charging.
CAC value same question.

Edwin
IMG_1282

**Comment by kallisti5** [comment]
A few fixes.

* I noticed the charging current was 0A on my car.  The formula changed for the Bolt from the Volt.
* Fixed the remaining xva -> xcb
* Added Ampera-e branding

Here's a summary of changes in the latest patchset
```diff
diff --git a/vehicle/OVMS.V3/components/vehicle_boltev/src/va_ac_preheat.cpp b/vehicle/OVMS.V3/components/vehicle_boltev/src/va_ac_preheat.cpp
index 759dad09..bef54800 100644
--- a/vehicle/OVMS.V3/components/vehicle_boltev/src/va_ac_preheat.cpp
+++ b/vehicle/OVMS.V3/components/vehicle_boltev/src/va_ac_preheat.cpp
@@ -71,10 +71,10 @@ const char * OvmsVehicleBoltEV::PreheatStatus()
 void OvmsVehicleBoltEV::ClimateControlInit()
 {
     // New VA specific metrics
-    mt_preheat_status       = MyMetrics.InitInt("xva.v.ac.preheat", SM_STALE_MIN, VA_PREHEAT_STOPPED);
-    mt_preheat_timer        = MyMetrics.InitInt("xva.v.ac.preheat_timer", SM_STALE_MIN, 0);
-    mt_ac_active            = MyMetrics.InitBool("xva.v.ac.active", SM_STALE_MIN, 0);
-    mt_ac_front_blower_fan_speed = MyMetrics.InitInt("xva.v.ac.front_blower_fan_speed", SM_STALE_MIN, 0, Percentage);
+    mt_preheat_status       = MyMetrics.InitInt("xcb.v.ac.preheat", SM_STALE_MIN, VA_PREHEAT_STOPPED);
+    mt_preheat_timer        = MyMetrics.InitInt("xcb.v.ac.preheat_timer", SM_STALE_MIN, 0);
+    mt_ac_active            = MyMetrics.InitBool("xcb.v.ac.active", SM_STALE_MIN, 0);
+    mt_ac_front_blower_fan_speed = MyMetrics.InitInt("xcb.v.ac.front_blower_fan_speed", SM_STALE_MIN, 0, Percentage);
 
     m_preheat_commander = Disabled;
 }
@@ -374,7 +374,7 @@ void OvmsVehicleBoltEV::PreheatWatchdog()
     }
     case VA_PREHEAT_STARTED: {
         if (m_preheat_commander==OVMS) {
-            unsigned int max_time = MyConfig.GetParamValueInt("xva", "preheat.max_time", VA_PREHEAT_MAX_TIME_DEFAULT);
+            unsigned int max_time = MyConfig.GetParamValueInt("xcb", "preheat.max_time", VA_PREHEAT_MAX_TIME_DEFAULT);
             if (mt_preheat_timer->AsInt() > 60 * max_time) {
                 ESP_LOGW(TAG,"Maximum preheat time reached. Stopping..");
                 PreheatModeChange(VA_PREHEAT_STOPPING);
@@ -415,7 +415,7 @@ OvmsVehicle::vehicle_command_t OvmsVehicleBoltEV::CommandClimateControl(bool ena
             CommandWakeup();
             vTaskDelay(720 / portTICK_PERIOD_MS);
         }
-        if (MyConfig.GetParamValueBool("xva", "preheat.override_bcm", false)) {
+        if (MyConfig.GetParamValueBool("xcb", "preheat.override_bcm", false)) {
             FlashLights(VA_PREHEAT_LIGHTS_STARTSTOP);
             m_preheat_commander = OVMS;
         } else
diff --git a/vehicle/OVMS.V3/components/vehicle_boltev/src/vehicle_boltev.cpp b/vehicle/OVMS.V3/components/vehicle_boltev/src/vehicle_boltev.cpp
index 3b7a2ccc..072bbd9a 100644
--- a/vehicle/OVMS.V3/components/vehicle_boltev/src/vehicle_boltev.cpp
+++ b/vehicle/OVMS.V3/components/vehicle_boltev/src/vehicle_boltev.cpp
@@ -658,10 +658,10 @@ void OvmsVehicleBoltEV::IncomingPollReply(canbus* bus, uint16_t type, uint16_t p
             NotifyFuel();
         break;
     case 0x4369:  // On-board charger current
-        StandardMetrics.ms_v_charge_current->SetValue((unsigned int)value / 5);
+        StandardMetrics.ms_v_charge_current->SetValue((unsigned int)value * 0.2);
         break;
     case 0x4368:  // On-board charger voltage
-        StandardMetrics.ms_v_charge_voltage->SetValue((unsigned int)value <<1);
+        StandardMetrics.ms_v_charge_voltage->SetValue((unsigned int)value << 1);
         break;
     case 0x801f:  // Outside temperature (filtered) (aka ambient temperature)
         StandardMetrics.ms_v_env_temp->SetValue((int)value/2 - 0x28);
@@ -1182,5 +1182,5 @@ OvmsVehicleBoltEVInit::OvmsVehicleBoltEVInit()
 {
     ESP_LOGI(TAG, "Registering Vehicle: Bolt EV (9000)");
 
-    MyVehicleFactory.RegisterVehicle<OvmsVehicleBoltEV>("CBOLT","Chevrolet Bolt EV");
+    MyVehicleFactory.RegisterVehicle<OvmsVehicleBoltEV>("CBOLT","Chevrolet Bolt EV / Ampera-e");
 }
```

**Comment by kallisti5** [comment]
As for the recall battery situation.  OpenEVSE wants a static battery value.  We could add a check box to the Bolt EV specific screen, but the language gets weird..

"Recall battery replaced in 2017-2019 vehicles" ?

The kWh changes from 60 kWh to 65 kWh if you have had the battery recall preformed.  In 2020+ vehicles the capacity doesn't change.

The estimated kWh is available within OBD and does change post-recall after the car learns the new battery pack size:
battery cap

**Comment by dexterbg** [comment]
Alex, I'm fine with merging this now if you are. You can fix the vehicle type metric later on. As it seems there are already users eagerly waiting for this, I think we should include it in the official edge build now, so you can collect more feedback.

OK for you?

**Comment by kallisti5** [comment]
sounds good to me.      I definitely will keep tuning it

**Comment by Edwintenhaaf** [comment]
Don't know if this is the right place but how can the app be updated with the Bolt and Ampera-e images ?
For the ampera-e  the best image I could find was this [one](https://medialibrary.stellantis.com/opel_press_gallery/download?&dl=ex&instance=admin1-medialibrary&sid=10&mid=1991102&orig=clipboard&ref=https%3A%2F%2Fwww.media.stellantis.com%2F)
It's from the opel media library. https://www.media.stellantis.com/be-nl/opel/images

**Comment by dexterbg** [comment]
Edwin,

the right places for App changes are the App repositories:
- https://github.com/openvehicles/Open-Vehicle-Android
- https://github.com/openvehicles/Open-Vehicle-iOS

For the basic car image integration, have a look at the recent BMW i3 addition by @dalathegreat :
- https://github.com/openvehicles/Open-Vehicle-Android/commit/549ef729c734d5c1b930ec42f311ca8a935f2c75

For overlay additions, see the Nissan Leaf lights, doors & charging overlays added by @drc38 :
- https://github.com/openvehicles/Open-Vehicle-Android/commit/2b164d818258cbab7ed10e05b4617fd6525babe1

Regards,
Michael

**Pull request merged**
