### PR TITLE
Fix for Kia e-Niro

### PR DESCRIPTION
**Pull request by Timopen**
Fix for Kia e-Niro hangs OVMS when car is off and no charging.
Fix for speed reading.
Wake up polling when car starts to charge again.

### CODE REVIEW

**Comment by glynhudson** [comment]
Is anyone with a E-niro able to test this? @goev @Timopen ? 

This is an issue effecting lots of users, see https://www.openvehicles.com/comment/5973#comment-5973

Maybe the "fix" could be included in a edge build so users without the ability to compile can test more easily?

**Comment by goev** [comment]
Hi Glyn,

I don’t have an E-Niro anymore, so I hope someone else can test this.

Best regards,
Geir / goev 

Sendt fra min iPhone

**Comment by Timopen** [comment]
Hi Glyn
I have been running the fix in my car for a while now.
And I made a binary on 3.2.005 last week and I it’s working great.
If someone else with an e-Niro is interested in testing I can share my binary.

Best Regards

TIMO PENTTILÄ
System Engineer/Developer

**Comment by toreblomhaug** [comment]
I would like to test please commit it to "edge" or link to binary :)

**Comment by Timopen** [comment]
Hi
Here is the link to the binary for the Kia e-niro fix:

https://drive.google.com/file/d/10-Of24Flqjsq-9P3a4LhWsCXka36JI1M/view?usp=sharing

Best Regards

TIMO PENTTILÄ
System Engineer/Developer

**Comment by glynhudson** [comment]
This "Fix" is now available in 'edge' releases, please report back any improved performance with E-Niro. See: https://www.openvehicles.com/comment/5994#comment-5994

**Comment by toreblomhaug** [comment]
Did update to edge,park and then move car 50 meter and charge it,still say parked and still same soc afther 7kw. Is this a known issue or was this supposed to be fixed?

**Comment by Timopen** [comment]
Hej Tore
Did you do a hard reset after the update?
If it still says that it’s parked at the original place, there is an issue with the server communication. How often do you update? Do you have the same issue if you use the binary that I linked to?

Med Vänlig Hälsning

TIMO PENTTILÄ
Systemtekniker/Utvecklare

Från: toreblomhaug <notifications@github.com>
Skickat: den 17 oktober 2019 10:49
Till: openvehicles/Open-Vehicle-Monitoring-System-3 <Open-Vehicle-Monitoring-System-3@noreply.github.com>
Kopia: Timo Penttilä <timo.penttila@codetap.se>; Mention <mention@noreply.github.com>
Ämne: Re: [openvehicles/Open-Vehicle-Monitoring-System-3] Fix for Kia e-Niro (#267)


Did update to edge,park and then move car 50 meter and charge it,still say parked and still same soc afther 7kw. Is this a known issue or was this supposed to be fixed?

**Pull request merged**
