### PR TITLE
Fix Server V3 client sending messages every minute

### PR DESCRIPTION
**Pull request by chris8086**
OVMS is a brilliant system, but I noticed that it was sending MQTT messages every minute, even when configured with updatetimes that were much longer than that. This activity consumes Hologram allowance and power unnecessarily.

The first step in fixing this is to filter out "clock" events, on the basis that they are of no use to anyone:
2024-11-10T22:52:00: Received PUBLISH from leaf (d0, q0, r0, m0, 'ovms/event', ... (10 bytes))
2024-11-10T22:52:00: Received PUBLISH from leaf (d0, q0, r0, m0, 'ovms/event/clock/2252', ... (0 bytes))
2024-11-10T22:53:00: Received PUBLISH from leaf (d0, q0, r0, m0, 'ovms/event', ... (10 bytes))
2024-11-10T22:53:00: Received PUBLISH from leaf (d0, q0, r0, m0, 'ovms/event/clock/2253', ... (0 bytes))
2024-11-10T22:54:00: Received PUBLISH from leaf (d0, q0, r0, m0, 'ovms/event', ... (10 bytes))
2024-11-10T22:54:00: Received PUBLISH from leaf (d0, q0, r0, m0, 'ovms/event/clock/2254', ... (0 bytes))
2024-11-10T22:55:00: Received PUBLISH from leaf (d0, q0, r0, m0, 'ovms/event', ... (10 bytes))
2024-11-10T22:55:00: Received PUBLISH from leaf (d0, q0, r0, m0, 'ovms/event/clock/2255', ... (0 bytes))

The second step is to amend Mongoose's keepalive timer, which defaults to 60 seconds. This timer generates these messages:
2024-11-16T12:11:06: Received PINGREQ from leaf
2024-11-16T12:11:06: Sending PINGRESP to leaf

This PR adds a new config parameter updatetime.keepalive, which is passed through to Mongoose.

I did some testing and identified that Hologram's TCP timeout is 30 minutes. For that reason, in this PR the default keepalive is set to 29 minutes in the hope that will be most sensible for most users. When OVMS metrics are published, Mongoose resets the keepalive timer so if the user has configured updatetimes less than that, PINGREQs will never need to be sent.

I'm happy to make changes to the PR if you'd prefer something a little different.

### CODE REVIEW

**Comment by dexterbg** [comment]
Chris, welcome.

Three things regarding this PR:
- Compare the full event name space prefix, i.e. including the dot: `clock.` (similar to the `ticker.` event filter).
- Add a user level explanation of the new config parameter to the `changes.txt` file. Include a brief info on how to test the timeout of the connection & MQTT hub used.
- Add the new config to the V3 web configuration UI -- all the other update intervals are already there, so this should be in the UI as well (and easy to add). Add the timeout test instructions there as well.

For later, you might consider adding another `IdIncludeExcludeFilter` as an `m_events_filter`, see the ServerV3's `m_metrics_filter` for reference. That way, users can easily define custom exclusions.

You also might consider adding a config switch to disable (or enable?) the legacy event publishing on the fixed `/event` topic.

Regards,
Michael

**Comment by chris8086** [comment]
Thanks Michael. I'll work on those. Regarding the last part, do you mean disabling legacy event publishing entirely? Happy to add that as well.

**Comment by dexterbg** [comment]
I mean making this …
https://github.com/openvehicles/Open-Vehicle-Monitoring-System-3/blob/470979369be56fe18eae0df90f1619afdd27e850/vehicle/OVMS.V3/components/ovms_server_v3/src/ovms_server_v3.cpp#L538-L541
… depend on a config.

**Comment by chris8086** [comment]
Ok, requested changes made, except the "for later" part. This work required a number of decisions (e.g. name of config parameter, where to put descriptive text) so I picked what seemed to make sense, but feel free to change them to suit.

**Pull request merged**
