### PR TITLE
Add Toyota RAV4 EV Support

### PR DESCRIPTION
**Pull request by mikeiimura**
Basic Toyota RAV4 EV support using only the Tesla CAN bus. Based on the existing Tesla Model S code.

The new vehicle web page uses dummy values hard coded because it won't compile when vehicle specific metrics are used.

"L:/OVMS/home/miimura/Open-Vehicle-Monitoring-System-3/vehicle/OVMS.V3/components/vehicle_toyotarav4ev/src/vehicle_toyotarav4ev.cpp: In static member function 'static void OvmsVehicleToyotaRav4Ev::WebCooling(PageEntry_t&, PageContext_t&)':
L:/OVMS/home/miimura/Open-Vehicle-Monitoring-System-3/vehicle/OVMS.V3/components/vehicle_toyotarav4ev/src/vehicle_toyotarav4ev.cpp:100:50: error: invalid use of member 'OvmsVehicleToyotaRav4Ev::m_v_bat_cool_in_temp' in static member function
   c.printf("<p>Battery Coolant Inlet: %.1f C</p>", m_v_bat_cool_in_temp->AsFloat());
                                                  ^
In file included from L:/OVMS/home/miimura/Open-Vehicle-Monitoring-System-3/vehicle/OVMS.V3/components/vehicle_toyotarav4ev/src/vehicle_toyotarav4ev.cpp:38:0:
L:/OVMS/home/miimura/Open-Vehicle-Monitoring-System-3/vehicle/OVMS.V3/components/vehicle_toyotarav4ev/src/vehicle_toyotarav4ev.h:90:22: note: declared here
     OvmsMetricFloat *m_v_bat_cool_in_temp;
                      ^
"
Anybody know how to fix that?

### CODE REVIEW

**Comment by dexterbg** [comment]
Michael,

as Steve already explained, if you want to access a member variable, you need to get the object (vehicle) pointer. You could do so by calling `MyVehicleFactory.ActiveVehicle()`.

But do you really want a static metric value in a web page? Why not use a standard metric display so you can see the dynamic value changes?

To do so, you simply need to add class "receiver" to e.g. your main panel div, then do:
```
  c.printf("<p>Battery Coolant Inlet: <span class=\"metric\" data-metric=\"xr4.v.b.t.cltin\">?</span> C</p>");
```
Or, using the metric number widget to get some default layout & style:
```
      <div class="receiver">
        ...
        <div class="metric number" data-metric="xr4.v.b.t.cltin" data-prec="1">
          <span class="label">Battery Coolant Inlet:</span>
          <span class="value">?</span>
          <span class="unit">°C</span>
        </div>
        ...
      </div>
```
See https://docs.openvehicles.com/en/latest/components/ovms_webserver/docs/metrics.html for the full reference.

Regards,
Michael

**Comment by mikeiimura** [comment]
Michael,

Thank you. I clearly did not do enough digging in the documentation to find
that excellent page describing exactly what I wanted to do. I was digging
in random vehicle code to find examples. Clearly a sub-optimal approach ;)

- Mike

**Comment by dexterbg** [comment]
From a first check of the code:
- Please change the vehicle code from "TY" to "TYR4", as we should expect future Toyota EVs additionally to the RAV4.
- Consider using all lower case URLs ("/xr4/cooling") to stick to our standard URL style.

**Comment by mikeiimura** [comment]
I have submitted a revised commit. The vehicle code is now "TYR4" as requested. The coded URL for displaying custom metrics was removed and implemented as a plugin, with the HTM provided.
The main difficulty I had was dealing with the 15 bit signed integer for the pack current. I had to declare some additional variables to manually decode it like this:

        fPackVolts = ((float)((int)d[1]<<8)+d[0])/100;
        iPackAmps = ((d[3]&0x3F)<<8) + d[2];
        if (d[3] & 0x40) fPackAmps = -0.1 * float(iPackAmps - 16384);
        else fPackAmps = -0.1 * float(iPackAmps);
        StandardMetrics.ms_v_bat_voltage->SetValue(fPackVolts);
        StandardMetrics.ms_v_bat_current->SetValue(fPackAmps);
        StandardMetrics.ms_v_bat_power->SetValue(fPackVolts * fPackAmps / 1000);

If anyone has a suggestion how to directly decode it without taking the 14 bit integer and testing the 15th sign bit, I would love it. Also, before I did the variable declarations "static" it would crash the OVMS within seconds of connecting the CAN. This is the beginning of the CAN1 procedure now.

void OvmsVehicleToyotaRav4Ev::IncomingFrameCan1(CAN_frame_t* p_frame)
  {
  
  uint8_t *d = p_frame->data.u8;
  static float fPackVolts;
  static float fPackAmps;
  static uint16_t iPackAmps;

**Comment by dexterbg** [comment]
Bit shifting is an option:

```
template <std::size_t NBITS>
int32_t packed_int(uint32_t val)
  {
  return ((int32_t)(val << (32-NBITS))) >> (32-NBITS);
  };

…

  fPackAmps = -0.1 * packed_int<15>(((d[3]&0x3F)<<8) + d[2]);
```

Declaring those local function vars `static` cannot solve a crash. That must have had another cause. Hint: use the `a2l` tool (see support directory) to decode backtraces.

Please remove the webserver asset file from the PR. Except for this and the missing documentation & history entry, this could be merged now.

Regards,
Michael

**Comment by mikeiimura** [comment]
Sorry I'm such a noob. Where am I supposed to put the "missing documentation & history entry"?

**Comment by dexterbg** [comment]
You've removed the RAV4 image now, but I meant the file `components/ovms_webserver/assets/charts.js.gz` -- maybe you need to add an exclusion rule to your `.gitignore`.

Just saw I made a copy/paste mistake on my code example, it should be…
```
  fPackAmps = -0.1 * packed_int<15>(((d[3]&0x7F)<<8) + d[2]);
```

Documentation:
- copy & adapt some vehicle's `docs/index.rst` into your `docs` folder
- add more info as needed, see other vehicle docs for inspiration
- test by doing a lokal sphinx build -- see https://github.com/openvehicles/Open-Vehicle-Monitoring-System-3/tree/master/docs
- add the link to the vehicle to the vehicle support list in the project's main `README.md` file

Add a history entry to: https://github.com/openvehicles/Open-Vehicle-Monitoring-System-3/blob/master/vehicle/OVMS.V3/changes.txt

**Comment by mikeiimura** [comment]
Don't know how that file got in the commit. I never added it.

I will take care of the documentation listed in the coming days.

**Comment by dexterbg** [comment]
Mike, any progress on this? A simple support sheet page would be sufficient for the documentation to start with.

**Comment by mikeiimura** [comment]
> Mike, any progress on this? A simple support sheet page would be sufficient for the documentation to start with.

I have not had time to work on it recently. The main reason I did not push ahead is that my build was not stable and working as expected. I hope to have a little more time to look at it again soon. I want to bring my branch up to the current master branch and then make sure my build environment is up to date. I was getting some messages during build that I think need to be addressed. Should I bring up those issues here on Github or on the dev mailing list?

**Comment by dexterbg** [comment]
Thanks for the feedback. Probably best to post your questions on the developer list.

When updating your master, I suggest doing that by rebasing, e.g. ``git pull --rebase --autostash``.

**Comment by dexterbg** [comment]
Michael, it seems you managed to update your repositories to a clean state & also did all necessary changes, so I'll merge this now.

Documentation is still an open todo: https://github.com/openvehicles/Open-Vehicle-Monitoring-System-3/pull/640#issuecomment-881848509

The minimum would be a line for `changes.txt` so `edge` users know about the new vehicle.

Regards,
Michael

**Pull request merged**
