### PR TITLE
Bolt EV: Better status reporting of DCFC sessions; fixes #705

### LINKED ISSUE #705: Bolt EV - DCFC is not detected
I took a trip to a DCFC station, and the OVMS doesn't realize when the vehicle is currently DCFC.   (It shows not charging still via the web ui)

Need to investigate which PID -> OVMS linkages are missing to properly detect CCS DCFC.

### PR DESCRIPTION
**Pull request by kallisti5**

### CODE REVIEW

**Comment by kallisti5** [comment]
I still need to test this.  Gives OVMS better information on charging conditions, and enables reporting of DCFC / CCS charging.

**Comment by kallisti5** [comment]
Level 2 charging detected properly, amps correct.  Detected start of charge and end of charge.

charging_1

not_charging

**Comment by kallisti5** [comment]
I need to test DCFC, however it will be a few days until i'm going to cross paths with a unit.

**Comment by dexterbg** [comment]
OK, waiting for your "go".

**Comment by kallisti5** [comment]
Hm.  So I had a chance to test this over the weekend.  While the level 2 charging is properly detected and the amperage is properly detected, DCFC is still completely undetected in the Android app  :-|

**Comment by dexterbg** [comment]
Alex, is this still WIP, or mergable?

**Comment by kallisti5** [comment]
I think it's fine to merge as-is.   It needs some more refinement but still represents an improvement to level 2 charging detection

**Pull request merged**
