### PR TITLE
Vehicle Shutdown - Wait for loop shutdowns and close down as nicely as possible

### PR DESCRIPTION
**Pull request by frogonwheels**
- Trying hard to avoid race conditions.
 - Signal loops so that we can shut down.

### CODE REVIEW

**Comment by dexterbg** [comment]
The task seems to have the shutdown handling twice?

Also, the task will `continue` after receiving a shutdown request, which means it will again call `xQueueReceive()`, so the queue doesn't become free to be deleted cleanly. It will work I think, but I suggest exiting the receive loop on either the shutdown request or detecting `m_shutdown` set, and doing the task deletion after the loop.

**Comment by frogonwheels** [comment]
I hear you.

The shutdown(true) should be called by the vehicle factory though before
the delete which waits a bit, giving time for the thread to shut itself
down.  So it really shouldn't be doing anything in the destructor... that's
more a just-in-case.

//.ichael

**Comment by frogonwheels** [comment]
Because of this code which is the only place where m_shut_down is set - it
immediately sends a Shutdown command to the poll task.
So m_shut_down flag just means the ONLY command that it will obey from then
on is the Shutdown task. By the time it gets to the queue being deleted the
task is most definitely shut down.

void OvmsPollers::ShuttingDown(bool wait)
  {
  if (m_shut_down)
    return;
  m_shut_down = true;
  if (m_polltask)
    Queue_Command(OvmsPoller::OvmsPollCommand::Shutdown, 0);

**Comment by frogonwheels** [comment]
This is what happens (Sorry – was not awake so making sure I’m not crossing my wires from what used to happen to what is happening now).

 

In going through this I made some minor adjustments along the lines of your suggestion.

 

When the event  ‘system.shuttingdown’ is fired.

 

*	Calls OvmsPollers::Shutdown(wait = true)

*	Sets m_shut_down =true.  This stops any command from being queued, and triggers the loop to be exited.

*  At some point from here, the loop exits and kills the tasks and then waits until it dies (??) 

*	Clears the queue and Sends a Shutdown command - which has the effect of making sure we stop waiting on the queue.
*	Unregisters events and callbacks
*	Clears the poller lists in the pollers
*	Waits for the poller task variable to be nulled for 2s
*	Deletes the task if it isn’t already .. but really it should be.
*	Deletes the queue
*	Powers down the can busses
*	Deletes the poller instances.

**Comment by dexterbg** [comment]
Minor notes:
- Instead of `xQueueReset()` followed by `xQueueSend()`, it's better to do `xQueueSendToFront()`.
- Suspending a task: `while(true) vTaskDelay(pdMS_TO_TICKS(10));` is a busy loop. You can do `vTaskSuspend(NULL)` or `vTaskDelay(portMAX_DELAY)`.
- `OvmsVehicle::VehicleTask()` is missing that task suspension.

**Comment by frogonwheels** [comment]
Agreed.
Will get that done.

**Pull request merged**
