### PR TITLE
CI: Add Travis-CI build script to build commits to the OVMS.V3 code.

### PR DESCRIPTION
**Pull request by chrisstaite**
Just needs Travis-CI.org to be configured for the repo and optionally a badge adding to the README.

### CODE REVIEW

**Comment by chrisstaite** [comment]
With the build issues on PRs I would recommend enabling travis-ci on this repository to detect them.

**Comment by dexterbg** [comment]
Chris, your script is in the repository, but apparently doesn't get triggered. Is there anything else we need to do?

**Comment by chrisstaite** [comment]
Yes, you just have to go and enable the repository at travis-ci.com

**Comment by dexterbg** [comment]
@markwj It seems you need to do this: I tried to add the OVMS3 repository using my Github account, the Travis CI setup worked for about a minute and then silently failed.

**Comment by dexterbg** [comment]
@markwj I got a build report from Travis 15 minutes later, it seems the setup actually finished in the background…? I'll see what happens with the next commit / PR.

**Comment by dexterbg** [comment]
Yes, it's functional now, PR #598 has been tested successfully. Thanks, Chris!

**Comment by chrisstaite** [comment]
Great! Maybe we can have builds pushed from it in the future?

**Comment by leres** [comment]
This is a pretty cool feature and it looks like I have the honor of submitting the first couple pull requests that exercise it!

ci

**Pull request merged**
