### PR TITLE
Mg4

### PR DESCRIPTION
**Pull request by GreyPeter**
I have finally finished my work on the MG4 code. I have tested it in my vehicle and it has been working well for quite some time. There a still a few tweaks I will do in the future but I think it is time for release.

### CODE REVIEW

**Comment by dexterbg** [comment]
Peter, awesome work!

**Comment by GreyPeter** [comment]
Thanks Michael,
Nice to hear.
Peter


On 30 Aug 2024, at 11:23 PM, Michael Balzer ***@***.***> wrote:

﻿

Peter, awesome work!

**Comment by lopezjm2001** [comment]
Does it include code for MG4 XPower?

**Comment by GreyPeter** [comment]
John, I believe the X-Power will probably work. Just select the 64kWh version. I would appreciate any feedback.
Peter

On 31 Aug 2024, at 7:49 PM, John Lopez ***@***.***> wrote:

﻿

Does it include code for MG4 XPower?

**Pull request merged**
