### PR TITLE
Valet Mode - add default valet mode with simple geofence

### PR DESCRIPTION
**Pull request by frogonwheels**
- Simply allowing 'Valet mode' without hardware support gives door detection anyway..
 - This adds the ability to have a Valet mode geofence radius from start location.

### CODE REVIEW

**Comment by dexterbg** [comment]
Michael, nice addition. This needs a bit of user documentation though, at least an entry to the `changes.txt` file.

**Comment by frogonwheels** [comment]
Ah yes.  Seeing as this is merged, how about I add a web config for it
(under vehicles) and add the doco?

Sorry about forgetting the doco. I'll get that done.

//.ichael

**Comment by dexterbg** [comment]
Reminded me of: https://docs.openvehicles.com/en/latest/userguide/locations.html

…so, the documentation for the standard flatbed alert system is also still missing. Would be appreciated if you could cover both.

**Comment by frogonwheels** [comment]
Will do, and I'll add them both to the ui if that is ok.

Michael

**Pull request merged**
