### PR TITLE
Climate Control working et al.

### PR DESCRIPTION
**Pull request by devmarxx**
We now have significant improvement on the VW e-UP (UpMiiGo) T26A implementation.

New Features are:
- Renaming from VWUP to VWUP.T26
- Prepared the app for handling VWUP and VWUP.T26
- Conflict detection for updates
- Charging detection 
- Setting of pre-heat/cool temperature in the webui
- Climate control working :-)
- Code prepared for the use of different vehicle ID's (more modular)
- Updated documentation

### CODE REVIEW

**Comment by glynhudson** [comment]
Awesome! Is this the new eUP?

**Comment by devmarxx** [comment]
Both. Old and new.

Am Donnerstag, den 03.09.2020, 13:09 +0000 schrieb Glyn Hudson:

**Comment by dexterbg** [comment]
Chris, great progress.

I think you've made a mistake on some master merge / rebase, you accidentally removed the commit including the `idtag` utility function and it's usage in the `can` subsystem. See the "Files changed" display here. Check your master merges, not sure how you could skip such an old commit. It may make sense to rebase your changes onto a freshly pulled master.

Regarding your code, you need to change your log tag and system extension namespace:

- Your log tag shall be `v-vweup-t26`.
- Your namespace for configs, metrics, commands, webpages etc. shall be `xut`.

See https://github.com/openvehicles/Open-Vehicle-Monitoring-System-3/pull/421#issuecomment-684976915 for details.

Please also take care you handled all compiler warnings.

Regards,
Michael

**Comment by devmarxx** [comment]
Thanx :-)
I changed the log tag and renamed the namespace.
I also rebased and pushed a freshly pulled master. Finally the mess
from the last weeks is now thoroughly cleaned up ...
The code compiles and runs without any warnings. The only warnings I
see a from the vw eup odb code. That is not within my responsibility
...
Regards
Chris


Am Freitag, den 04.09.2020, 05:42 -0700 schrieb Michael Balzer:

**Pull request closed without merging**
