### PR TITLE
Improve wakeup message

### PR DESCRIPTION
**Pull request by dalathegreat**
Noticed while testing on various LEAFs that it doesn't always wake them up. Added another message that helps :)

### CODE REVIEW

**Comment by mjkapkan** [comment]
Yeah previous stuff did not work for me. Will try it out. It might depend on the firmware in the car as well.

**Comment by dalathegreat** [comment]
For future reference, here are all the wakup messages that the LEAFs use. env200 might be different, haven't got enough logs.
x68C CAR-CAN (2013+)
x682 CAR-CAN ? 
x603 CAR-CAN (2011-2012)
x68C EV-CAN (2013+)
x679 EV-CAN (all)
x603 EV-CAN (2011-2012)

**Comment by drc38** [comment]
@dalathegreat what's the logic behind sending x679 twice to the same bus, wouldn't be better to add another message on the other bus eg x68c or same x679 message on the other bus?

**Comment by mjkapkan** [comment]
For me the only way all metrics are updated when vehicle is not charging or plugged in is by sending charge stop message. Will try to check which frames actually trigger it

**Comment by dalathegreat** [comment]
> @dalathegreat what's the logic behind sending x679 twice to the same bus, wouldn't be better to add another message on the other bus eg x68c or same x679 message on the other bus?

The LEAF has some modules that operate only on EV-CAN, and some only on CAR-CAN. It is quite common for the VCM to copy messages from one bus to the other. For example copy ABS info from CAR -> EV.

**Pull request merged**
