### PR TITLE
add support fro maxus eDeliver3

### PR DESCRIPTION
**Pull request by KilveEng**
added support so far for the following
SOC
pack voltage
charge power
charge amps
odometer

### CODE REVIEW

**Comment by dexterbg** [comment]
Shane,

thanks for the submission. I've got some minor change requests:

- Please rename your vehicle name "eDeliver3" & component "edeliver" to include the manufacturer name first, possibly shorten both if that gets too long. Your short name "MED3" is fine.
- Use the component specific macro in your `component.mk` instead of `CONFIG_OVMS_VEHICLE_NONE`.
- Add some documentation, at least the usual boiler plate page containing the features supported so far. Example/template: https://docs.openvehicles.com/en/latest/components/vehicle_renaultzoe/docs/index.html – don't forget to add the link to the top level `README.md`.
- Add an entry to the `changes.txt` file (user level change history).

Not a strict necessity, but a general recommendation: clean up your code with regards to a) code style (primarily indentation style) and b) dead code, seemingly remains of some copy & pastes from another module.

Regarding code style, there's a nice automatic tool called "astyle" for this. Example configuration: https://github.com/openvehicles/Open-Vehicle-Monitoring-System-3/blob/master/vehicle/OVMS.V3/components/vehicle_vweup/src/.astylerc

You can keep this PR open, further changes submitted to your `master` will automatically be added here.

Regards,
Michael

**Comment by KilveEng** [comment]
Evening Michael, 

Thank you for your feedback, Please bear with me im new to this, 

Point  	1. I’ve changed all the names now,
		2. Think I’ve updated this correct
		3. Ive followed the link but can't find where to add mine?? 
		4. Ill prob find this when I find point 3!

I’m having a tidy up of the style etc, just trying not to break what I’ve done by deleting something I need ;-) and will look into using the “astyle” tool to improve my work

Regards

Shane

**Comment by dexterbg** [comment]
Shane,

create a docs directory in your component, copy the `index.rst` file from the Zoe component and change the content accordingly. The file will be added to the documentation menu automatically. You can test that by doing a local build, see `docs/README.md` on how to install sphinx locally. The link in the main `README.md` needs to be added manually once the URL is known. See other links there on how to form the URL.

The `changes.txt` grows at the top, add your entry after the "??" line. Use another "New vehicle" entry from that file as a template.

Regards,
Michael

**Comment by KilveEng** [comment]
Thanks Michael for your offer!

I’ll have a look at it tomorrow and if I get stuck I’ll give you a shout 

Regards
Shane Hunns

**Pull request merged**
