### PR TITLE
Vehicle zoe

### PR DESCRIPTION
**Pull request by mmezog**
Here is my initial support for the Renault Zoe. I've based it on the v2 Zoe, and the v3 Kia Soul and Nissan Leaf.

Seems to be working on my car.

I hope to find more time to add further metrics and maybe add support for the android app.
This is probably my first C++ and embedded project so I hope to not break anything.
Thanks

### CODE REVIEW

**Comment by dexterbg** [comment]
Marcos, thanks for submitting your work, which looks good. I normally would merge this now.

I've got a little dilemma I'd like to address before I do: Wolfgang Jenne @wolfijenne, the author of the V2 Zoe support, also has been working on V3 support, and his code is more advanced than yours. You can find his code here:
https://github.com/wolfijenne/Open-Vehicle-Monitoring-System-3

Wolfgang hasn't created any pull request for it yet, so technically you're first now. But I'd like to give him the chance to join in here, maybe you can find a way to merge your efforts.

I'll inform him now.

**Comment by mmezog** [comment]
No problem. I didn't know Wolfgang's work even existed, otherwise I wouldn't have started my port or I would have worked to extend his code. You can ask him to merge his changes and drop my pull request. As you say, his code is much more advanced than mine. I'll work from that code too.

Btw. I mentioned the v2 Zoe code, but I didn't see v2 Wolfgang's code either, I just saw some basic code by you (Dexter) in the "official" openvehicles repo,  more or less the same as i have now.

Thank you,

**Comment by dexterbg** [comment]
Oops, you're right, there wasn't a pull into V2 either.

Wolfgang told me he hasn't got the time to continue his work on the Zoe support, and he would like you to pickup his results. He asked me to forward you his email address in case you need some info regarding his code, I'll do so by email.

Shall I merge your pull request now to become the Zoe base implementation, or do you want to use his fork as your base?

**Comment by beckerstef** [comment]
very nice I'm waiting for a long time, hope I can test it soon.
 @wolfijenne thank you for sharing your work with @mmezog

**Comment by beckerstef** [comment]
I think @mmezog has included the code from @wolfijenne, or am I wrong?

**Comment by dexterbg** [comment]
There's new code in his repository, but the pull request is unchanged. Marcos, are you still testing?

**Comment by dexterbg** [comment]
@mmezog  Marcos, any news on the Zoe merge?

**Comment by glynhudson** [comment]
Any progress on this? It would *awesome* to have Zoe support included in OVMS

**Comment by glynhudson** [comment]
I've just tested `3.2.002` edge and Zoe is not displaying as a vehicle option 

```
OVMS# vehicle list
Type Name
DBC  DBC based vehicle
DEMO Demonstration vehicle
FT5E Fiat 500e
KN   Kia Niro EV
KS   Kia Soul EV
MI   Trio
NL   Nissan Leaf
NONE Empty vehicle
O2   OBDII
RT   Renault Twizy
SE   Smart ED 3.Gen
SQ   Smart ED/EQ 4.Gen
TGTC Think City
TR   Tesla Roadster
TS   Tesla Model S
VA   Volt/Ampera
XX   TRACK
ZEVA ZEVA BMS
```

```
OVMS# ota status
Firmware:          3.2.002-223-gd16a731/ota_0/edge (build idf v3.3-beta3-772-gc3465e0 Sep 10 2019 00:00:13)
```

**Pull request merged**
