### PR TITLE
Obd2 ext new handling

### PR DESCRIPTION
**Pull request by SokoFromNZ**
Hi @Dimitrie78 and @dexterbg 

Here is the change of the `case VEHICLE_POLL_TYPE_OBDIIEXTENDED` in `PollerReceive()` we talked about.

Like this it works for the VW e-Up.

In addition I changed the send interval according to the msgs VCDS is sending. In addition I want the full data asap...

Let me know your thoughts

Soko

### CODE REVIEW

**Comment by dexterbg** [comment]
Soko, please wait with further work on this topic. I'm thinking about a rewrite of the poll receiver, as it has some long known shortcomings along with the bug we detected. 

Regards,
Michael

**Comment by SokoFromNZ** [comment]
Okeydokey. Let me know here if you have a rewrite...

**Comment by drc38** [comment]
Is there any reason to set the interval for extra frames at 1ms? `txframe.data.u8[2] = 0x01; // with 1 ms send interval (as fast as possible)` I note the Leaf is ok with it being set to 0. Would it make sense to be able to alter this value by vehicle type?

**Comment by dexterbg** [comment]
@drc38 I've already taken this into account in my yet to publish rework.

**Comment by dexterbg** [comment]
Rewrite of the poller receiver is now pushed in branch `poller-rework`:
https://github.com/openvehicles/Open-Vehicle-Monitoring-System-3/commit/0b306ad4f5e7a1eb63a471a11ec7f1a6d69d8647

The rewrite obsoletes all or most of this PR, so I'll close this now. If you want to add to the poller rework, please create a PR for that branch.

**Pull request closed without merging**
