### PR TITLE
Add Aux 12v battery monitor to vehicle class  (with scripting and duktape intf)

### PR DESCRIPTION
**Pull request by frogonwheels**
Moved the battery monitor from the Ioniq5 implementation.

Added internal support for enable/disable and extended run-time config.

Add duktape support for aux battery monitor

Add cli support as well.

### CODE REVIEW

**Comment by dexterbg** [comment]
(Now at the correct PR…)

Michael, I'm getting sphinx errors from your documentation changes, please fix:
```
/home/balzer/esp/Open-Vehicle-Monitoring-System-3/docs/source/userguide/scripting.rst:1034: WARNING: Block quote ends without a blank line; unexpected unindent.
/home/balzer/esp/Open-Vehicle-Monitoring-System-3/docs/source/userguide/scripting.rst:1035: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/home/balzer/esp/Open-Vehicle-Monitoring-System-3/docs/source/userguide/scripting.rst:1042: WARNING: Definition list ends without a blank line; unexpected unindent.
```

Also, the sphinx output from these changes is broken -- not yet visible on the RTD page, but you can check it by a local build.

**Comment by frogonwheels** [comment]
Could you please fix them.

I really tried to get sphinx working on wsl+Ubuntu  but I can't get the
right bits installed!


//.

**Comment by dexterbg** [comment]
Sure.

**Comment by frogonwheels** [comment]
Thanks. I will have another go at it sometime but something has changed
with the config of pip etc that I have yet to get my head around.

Michael

**Comment by dexterbg** [comment]
Done, see commit 470979369be56fe18eae0df90f1619afdd27e850

You need to take care to insert the exact amount of spacing and indentation, i.e. there needs to be a blank line before and after a `code-block` directive, indentation needs to be in multiples of 2 spaces, and the code block itself needs to be indented one level more than the directive.

**Pull request merged**
