### PR TITLE
WIP NL: Fix charge climit spam for ZE0

### PR DESCRIPTION
**Pull request by dalathegreat**
Affects 2011-2012 Nissan LEAF with master branch. See https://github.com/openvehicles/Open-Vehicle-Monitoring-System-3/issues/684

Will test this on a LEAF as soon as I get the chance, not available for me at the moment.

Test build available here: https://dalasevrepair.fi/wp-content/OVMS/ovms3.bin

### CODE REVIEW

**Comment by dexterbg** [comment]
Daniel, Peter sent me some new logs using your test build. It doesn't help yet. Example:

```
15:58:44 S24.0,M,220,23.18,charging,standard,31,24,23,2819,0,40,13,1,0,0,0,0,67.80,269,0,0,0,-1,0,0,0,0,0,102,0,5.23,348.50,85,5.10,100.00,-15.00,22.6
15:58:45 S24.0,M,220,23.18,charging,standard,31,24,23,2820,0,40,13,1,0,0,0,0,67.80,269,0,0,0,-1,0,0,0,0,0,102,0,5.23,348.50,85,5.10,100.00,-15.00,22.6
15:58:47 S24.0,M,220,23.64,charging,standard,31,24,23,2822,0,40,13,1,0,0,0,0,67.80,269,0,0,0,-1,0,0,0,0,0,102,0,5.23,348.50,85,5.20,100.00,-15.00,22.6
15:58:48 S24.0,M,220,23.18,charging,standard,31,24,23,2823,0,40,13,1,0,0,0,0,67.80,269,0,0,0,-1,0,0,0,0,0,102,0,5.23,348.50,85,5.10,100.00,-15.00,22.6
15:58:49 S24.0,M,220,23.18,charging,standard,31,24,23,2824,0,40,13,1,0,0,0,0,67.80,269,0,0,0,-1,0,0,0,0,0,102,0,5.23,348.50,85,5.10,100.00,-15.00,22.6
15:58:53 S24.0,M,220,23.18,charging,standard,31,24,23,2828,0,40,13,1,0,0,0,0,67.80,261,0,0,0,-1,0,0,0,0,0,102,0,5.23,348.50,85,5.10,100.00,-15.00,22.6
15:58:54 S24.0,M,220,23.18,charging,standard,31,24,23,2829,0,40,13,1,0,0,0,0,67.80,261,0,0,0,-1,0,0,0,0,0,102,0,5.23,348.50,85,5.10,100.00,-15.00,22.6
```

I'll send a full S log to you by email.

Regards,
Michael

**Comment by dalathegreat** [comment]
The 87d2abc commit has all climit uncommented, which stopped the spam

Now it is time to start adding them back one by one and see where it goes wrong.

**Comment by dalathegreat** [comment]
Test build of e4f713f available here: https://dalasevrepair.fi/wp-content/OVMS/ovms3.bin

**Comment by dexterbg** [comment]
Daniel, is this still WIP or can I merge this?

**Comment by dalathegreat** [comment]
Sadly not, I sold my ZE0 LEAF so I have no test vehicle anymore!

**Pull request closed without merging**
