### PR TITLE
Kia Soul Branch

### PR DESCRIPTION
**Pull request by goev**
Fixed problem setting charge state.

### CODE REVIEW

**Comment by dexterbg** [comment]
Geir, does this pull request actually contain any changes not yet merged? It looks like you just did some local restructuring of commits. If you're testing some rebasing, I recommend not to do that with commits already merged upstream.

**Comment by goev** [comment]
There’s only one file that has been changed by me: components/vehicle_kiasoulev/src/vehicle_kiasoulev.cpp
I can see it in the pull request. It is not a huge thing, but without it, the app won’t recognize the charging state properly. 

I must admit that Git is confusing me a bit. I did the rebase-thing before commit. Was that wrong?

Geir

**Comment by dexterbg** [comment]
No problem, I just wanted to check.

**Comment by goev** [comment]
Thanks for checking 🙂

**Pull request merged**
