### PR TITLE
NL charge stop

### PR DESCRIPTION
**Pull request by MikMudry**
Merged @markfinn 's 1db method to stop charge of Nissan Leaf into current branch.
Issue #287 Possible to add stop charging on Nissan Leaf?

### CODE REVIEW

**Comment by mjkapkan** [comment]
I tested this as well. However, the scheduled charging might not work after the car charging was stoped using this method Unless re-plugged. Anyway still worth having, so should be added.

**Comment by dexterbg** [comment]
I would normally ask for some code cleanup here regarding indentation/block style and member variable naming. Also, what is the purpose of `last1db`? Seems to be unnecessary…?

But @mjkapkan, if you're ok with this, I can merge it anyway.

**Comment by markfinn** [comment]
> what is the purpose of last1db? Seems to be unnecessary

It is.  I must have been planing on using it to send one 1db packet out right away when the charge stop command came in, but that doesn't look like I implemented it.

It still would be worth following up on the idea in #287  to try to avoid the car noticing what we're doing and throwing an error.  I don't remember if I got very far in trying it back when it was discussed.

**Comment by mjkapkan** [comment]
Unfortunately my car is under repair after front collision for over 3 weeks now. Hopefully I can get the car back next week and verify the code. Another question,  has anyone tested this on other MY cars?

**Comment by dalathegreat** [comment]
Could @MikMudry remove the `last1db` and we could maybe get this one merged? :) I have been using this method now for 3 years to stop the charge (every single charge!), so it is fair to say that it is not wearing out the contactors like theorized in the linked thread.

**Comment by dalathegreat** [comment]
This PR can be rejected and closed, functionality merged in #662
@dexterbg

**Pull request closed without merging**
