### PR TITLE
NL: Add stop charge + document update + vehicle wakeup fix

### PR DESCRIPTION
**Pull request by dalathegreat**
It pains me to see the that the #651 pull request opened in September is still up. To remedy this, I cleaned it up slightly, and made some improvements to the documentation. When this is merged, we finally have stop charge ability for the Nissan LEAF :)

BIN file for testing: https://dalasevrepair.fi/wp-content/OVMS/ovms3.bin

### CODE REVIEW

**Comment by dexterbg** [comment]
Daniel,

as you're one of the maintainers of the Leaf code, you may of cource choose to change the code style, but I wouldn't do a correct review without mentioning this: class member variables have up to now been mostly consistent to use the standard `m_` name prefix.

Are you OK with breaking the naming style on this PR?

Side note: using the same function name with just a case switched first letter on both a static and a member function may also be confusing to other developers (`mITMDisableTimer` vs `MITMDisableTimer`). I'd rather add some suffix like `Callback` to the timer callback name.

Regards,
Michael

**Comment by dalathegreat** [comment]
Thanks for the feedback, I made the naming hopefully a bit more clear in commit 248fd7b

I also fixed the vehicle wakeup command issue that was reported back in issue #544 . The code now uses correct message for all generations. I have confirmed that the code works on my own LEAFs.

**Comment by mjkapkan** [comment]
Thanks @dalathegreat, such a nice Christmas present!💝 Will test this on MY13.

**Comment by dexterbg** [comment]
Seems you missed `int MITM`…?

**Comment by dalathegreat** [comment]
Whoops, fixed in d713a36 . This should now be ready to merge!

**Comment by MikMudry** [comment]
Nice, works for me and my 2014 Leaf. Thank you, @dalathegreat , Leaf owners are glad for this present!
Sorry for not responding few days ago in the original pull request.

**Comment by mjkapkan** [comment]
Regarding the documentation. I see it went directly in to official OVMS support page. So users might expect functionality to work in the main release channel. @dexterbg do we have any way to handle this? Or this just haven't been a big problem so far?

**Comment by dexterbg** [comment]
The OVMS documentation hosted by readthedocs includes two versions, "latest" and "stable". Users on the "main" release branch should use "stable". You can easily switch between the versions using the menu on the left bottom, or you can bookmark the respective version URL:
- https://docs.openvehicles.com/en/stable/
- https://docs.openvehicles.com/en/latest/

**Comment by mjkapkan** [comment]
Ah okay, that makes sense! Thanks! Then I guess it is more of google indexing thing as when you search "ovms nissan leaf support" the first link leads to the edge documentation. And especially in mobile view the indication of release branch is not that easily visible.

**Comment by dexterbg** [comment]
May also be due to us including only the "latest" link to the main README and on the project websites.

There's issue #642 on this topic. I've added both links to the README and a note on the intro page.

**Comment by mjkapkan** [comment]
Tested the charge stop feature. Works quite well. However just as with the last implementation I tried if you start climate control while plugged in, after climate control is stopped, it does not stop the charge. We might need to add a variable that would track charge requests separately from car's VCM. I will register a separate issue to handle that.

**Comment by niallm90** [comment]
I have been testing this myself and I'm not seeing the metrics being updated after I stop the charge. I'm using my own MQTT server and the V3 metrics with the tip of master as of last night (a0a3641).

I started a charge by connecting the charger. I get metrics reported back including charge state and the current draw. Then when I stop the charge the charge stops reliably however I don't get any metrics back to report the car is no longer charging. The charge state and current don't updated from the last reported values while charging.

Let me know if I can be of further help debugging this.

**Comment by mjkapkan** [comment]
@niallm90 Please try the firmware from PR #676 I have enhanced the charging metrics there, so hopefully it will work with your vehicle as well.

**Comment by niallm90** [comment]
@mjkapkan Using 4716592 I'm still seeing the same behavior. I get a charge stopped event but none of the charging related metrics are updated. Here is the output from the console when I start and stop a charge. This is with info level debugging, let me know if you would like something more detailed.

```
I (148239) ovms-server-v3: Tx event notify.info.charge.started
I (148369) ovms-server-v3: Message publishing acknowledged (msg_id: 233)
I (151229) ovms-server-v3: Tx event vehicle.charge.12v.start
I (151499) webserver: HTTP POST /api/execute
I (151499) webcommand: HttpCommandStream[0x3f8c0b18]: 3478188 bytes free, executing: stat
I (152229) powermgmt: Charging 12V battery..
I (165109) webserver: HTTP POST /api/execute
I (165109) webcommand: HttpCommandStream[0x3f8c0b18]: 3478296 bytes free, executing: charge stop
I (165109) v-nissanleaf: CommandStopCharge - MITM method
I (165209) v-nissanleaf: MITM attempted off
I (165209) v-nissanleaf:  MITM turned off
I (166269) ovms-server-v3: Tx event vehicle.charge.stop
I (166269) ovms-server-v3: Tx event vehicle.charge.state
I (166269) ovms-server-v3: Tx event vehicle.charge.mode
I (166439) webserver: HTTP POST /api/execute
I (166449) webcommand: HttpCommandStream[0x3f8b6e34]: 3474352 bytes free, executing: stat
I (166459) webserver: HTTP POST /api/execute
I (166459) webcommand: HttpCommandStream[0x3f8c0b18]: 3464228 bytes free, executing: stat
I (166479) webserver: HTTP POST /api/execute
I (166479) webcommand: HttpCommandStream[0x3f8c07f0]: 3456244 bytes free, executing: stat
I (171229) ovms-server-v3: Tx event vehicle.charge.12v.stop
I (171359) webserver: HTTP POST /api/execute
I (171369) webcommand: HttpCommandStream[0x3f8c0b18]: 3476448 bytes free, executing: stat
I (172229) powermgmt: No longer charging 12V battery..
I (192139) webserver: HTTP GET /shell
I (200229) ovms-server-v3: Tx event clock.1125
```

**Comment by mjkapkan** [comment]
@niallm90 I just checked the metrics and they are updated normally. The only thing that went bad with the latest change was that the charge time estimation was wrong. I fixed that in the latest #676 update. Feel free to test the updated firmware. However if it still doesn't work, can you provide names of the specific metrics that are not updated?

**Pull request merged**
