### PR TITLE
add trip time to trip report

### PR DESCRIPTION
**Pull request by sharkcow**
good for comparing different regular routes as to which is the fastest one :)

this time with better data types and display (thanks to Michael) :D

### CODE REVIEW

**Comment by kezarjg** [comment]
Seems like this PR undid #920 . Was that intentional?

**Comment by sharkcow** [comment]
No, that must be my mistake... probably I didn't rebase correctly before submitting the PR. Sorry about that, but I'm sure Michael can fix it? ;-)

**Comment by dexterbg** [comment]
Your rebase was correct, you had the change in your tree and then exchanged the corresponding lines by your new implementation, see the diff:

https://github.com/openvehicles/Open-Vehicle-Monitoring-System-3/pull/1068/files#diff-b14ceb0c85188acc87d16961bbbc8c600afae3ee23d5f61b2ba839da55cdc245L1514-L1531

This looks totally intentional. If it wasn't, please merge your intended change with the one by @kezarjg and create a new PR.

**Comment by sharkcow** [comment]
OK, I have no idea what I did there. I sincerely apologize for damaging your code, @kezarjg. I will correct and re-submit.

**Comment by kezarjg** [comment]
No sweat. It's our code...

**Pull request merged**
