### PR TITLE
Maxus eDeliver3 update to enable app data to work

### PR DESCRIPTION
**Pull request by KilveEng**

### CODE REVIEW

**Comment by dexterbg** [comment]
Shane,

the change to mg_poll_bms (add cell deviation) cannot be accepted for two reasons:

1. PRs must not mix topics or vehicles. The only exception is some overall API / framework change that involves updates to multiple vehicle modules.
2. `ms_v_bat_pack_vstddev` must not be used for anything else than the cell voltage standard deviation. I.e. the change also cannot be accepted in a separate PR.

Please remove that change from the PR.

Regards,
Michael

**Comment by KilveEng** [comment]
Hi Michael, 

Still getting to grips with git hub sorry, I had unticked the mg part when I committed the maxus charges but for some reason it was still there?? 

Also the ms_v_bat_pack_vstddev is the standard cell deviation for the mg 

Il will try again to pull just the maxus 

Shane

**Comment by dexterbg** [comment]
You now have deleted the mg file. To create a pull request for selected commits: create a branch, work in that branch or cherry-pick the commits you want to get merged, then create a PR for that branch.

**Comment by KilveEng** [comment]
How do you cherry pick the commits? Ive closed the pull request for now till I get this right!

Shane

**Comment by dexterbg** [comment]
- `git cherry-pick <commit>`
- `gitk` → context menu on commit → Cherry-pick this commit

**Pull request closed without merging**
