### PR TITLE
new metrics for maintenance/service, transmit via server v2

### PR DESCRIPTION
**Pull request by sharkcow**
separate PR only for maintenance metrics as discussed.

### CODE REVIEW

**Comment by dexterbg** [comment]
Thanks, looks much better. Just one issue left: I think you misread the unit `TimeUTC` to represent the Unix time (epoch), which is understandable given there are currently only `TimeUTC` and `TimeLocal` as explicit timestamp-like units defined.

The right unit (for now) is `Seconds`, as with `m.time.utc`. `TimeUTC` and `TimeLocal` actually get converted to a time of day, with string format scheme `HH:MM:SS`. These are used for scheduler entries (timed charging etc.).

Another option, if you'd like to go that far: add unit support for `DateUTC` & `DateLocal`, and/or `DateTimeUTC` & `DateTimeLocal`.

Regards,
Michael

**Comment by sharkcow** [comment]
Thanks for your feedback. Just corrected the units as a quick fix, please merge. If I find more time, I'll look into the unit support.

**Comment by dexterbg** [comment]
No changes, did you push?

**Comment by sharkcow** [comment]
Oops, sorry :-/ Now I did :)

**Pull request merged**
