### PR TITLE
RAV4 EV updates

### PR DESCRIPTION
**Pull request by mikeiimura**
Final updates to Tesla-Only version. Subsequent contributions will also involve the Toyota bus on second CAN bus.
I don't know why the zlib was changed in my build environment. the .gitignore was an attempt to block that from being contributed upstream.

### CODE REVIEW

**Comment by dexterbg** [comment]
Mike, your PR contains a change to `.gitignore`. That's a) wrong (the change) and b) must not be included in a vehicle PR.

I assume you've had git telling you there is a change in the submodule, so you decided to add that to the ignore list. Git telling you there is a change in a submodule means you need to update your submodule, not ignore the change.

Regards,
Michael

**Comment by mikeiimura** [comment]
> Mike, your PR contains a change to `.gitignore`. That's a) wrong (the change) and b) must not be included in a vehicle PR.
> 
> I assume you've had git telling you there is a change in the submodule, so you decided to add that to the ignore list. Git telling you there is a change in a submodule means you need to update your submodule, not ignore the change.
> 
> Regards, Michael

Michael, what is the right way to fix this? Do I delete the pull request and submit a fixed one or is there a way for me to modify the request? The root of the problem is the change to GitHub where it would not authenticate the 'git' inside Mingw32 but I had to install GitHub Desktop to get it to connect my fork on GitHub to the repository I was compiling in Mingw32 for testing on my module.

**Comment by dexterbg** [comment]
Simply revert the change to `.gitignore` in your PR branch, the PR will automatically be updated by pushing.

**Comment by mikeiimura** [comment]
> Simply revert the change to `.gitignore` in your PR branch, the PR will automatically be updated by pushing.

Sorry I'm being so dense here. Where to I click to "revert" the .gitignore? I am assuming I can do it completely on the GitHub site. Is that my problem? Do I have to push the change back up from my local machine repository?

**Comment by dexterbg** [comment]
You should be able to edit the file on github as well, open
https://github.com/mikeiimura/Open-Vehicle-Monitoring-System-3/blob/master/.gitignore
…then click on the pencil on the upper right. Remove your zlib line, commit the change.

**Comment by mikeiimura** [comment]
Thanks Michael. That looks like it worked. The PR no longer includes the file.

**Pull request merged**
