### PR TITLE
NL: use setpoint to indicate hvac status

### PR DESCRIPTION
**Pull request by drc38**
change from using fan speed as it can result in hvac reporting as on when it is not

### CODE REVIEW

**Comment by mjkapkan** [comment]
We have extensively tested the behaviour with @ankohanse last year and it seem to work for both 2013 and 2016 models. Under what conditions you see it as ON?

**Comment by drc38** [comment]
@mjkapkan here are my metrics when it reports as hvac on, with a solar panel if cabin temp is high does run fan at low speed for circulation?
v.e.alarm
v.e.aux12v
v.e.awake                                yes
v.e.c.config
v.e.c.login
v.e.cabinfan                             3%
v.e.cabinfanlimit                        7
v.e.cabinintake                          fresh
v.e.cabinsetpoint                        0°C
v.e.cabintemp                            25.5556°C
v.e.cabinvent                            face
v.e.charging12v                          yes
v.e.cooling                              no
v.e.drivemode
v.e.drivetime                            0Sec
v.e.footbrake
v.e.gear                                 0
v.e.handbrake                            yes
v.e.headlights                           no
v.e.heating                              no
v.e.hvac                                 yes
v.e.locked                               no
v.e.on                                   no
v.e.parktime                             612Sec
v.e.regenbrake
v.e.temp                                 23°C
v.e.throttle                             0%
v.e.valet

**Comment by mjkapkan** [comment]
I see. Let's try it out then.

**Comment by drc38** [comment]
@mjkapkan yes that's my view, as you want to know when there's a significant power draw from heating or cooling. Strictly speaking hvac includes ventilation but this appears to be a feature on solar panel models and is not controllable by the user (either in car or with ovms).

**Comment by drc38** [comment]
@mjkapkan also noticed v.e.cabinfan reports 3%, does this metric need scaling based on the fanlimit?

**Comment by mjkapkan** [comment]
@drc38 The cabinfan was added before it was a part of standart metrics, so it actually represents the exact steps you can see on the dash. I personally did not agree with having the metric in percentage as it adds additional calculation requirements to the GUI. And usually what user needs is total steps and current step. But I guess it is now decided so we need to go with the flow. You can do that by multiplying it by 100 and dividing by fanlimit.

**Comment by drc38** [comment]
@mjkapkan for my 2016 model remote cooling wasn't being identified in the code, so a few more tweaks required. <2013 should be unaffected.

**Comment by drc38** [comment]
@dexterbg ok to merge? As I have a couple of other fixes on this file to submit. Thx

**Pull request merged**
