### PR TITLE
Metrics - Clarify which virtual methods are overridden

### PR DESCRIPTION
**Pull request by frogonwheels**
- Some overrides were marked virtual
 - Mark all overridden methods with 'override'

### CODE REVIEW

**Comment by frogonwheels** [comment]
This P/R is a tidy-up only and is about clarity rather than any fixes.

**Comment by dexterbg** [comment]
Michael,

if we go that path, shouldn't we also tag the destructors as `override`?

Apparently, the C++ core guidelines once suggested not doing so, but the editors have changed their mind:

- https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rh-override
- https://github.com/isocpp/CppCoreGuidelines/pull/1448
- https://github.com/isocpp/CppCoreGuidelines/issues/721#issuecomment-598878968

Regards,
Michael

**Comment by frogonwheels** [comment]
Assuming they are virtual destructors in the base then absolutely I think
it's  a good idea.


Michael

**Comment by frogonwheels** [comment]
I have another interesting and related observation:

Virtual destructors should only be used if a class would be destroyed via a
base class.  This absolutely applies to OvmsMetric  but I don't think it
should apply to OvmsMetrics (which is a singleton) or MetricCallbackEntry.
We are unnecessarily creating a vtable for the class just for the
destructor!

Are you OK if I remove 'virtual' from the destructors of these 2?  In the
same P/R? I can do a separate P/R if needed - I'll definitely do a
separate commit anyway.

//.ichael

**Comment by dexterbg** [comment]
Perfectly OK to add here, those are most probably copy & paste errors.

**Pull request merged**
