### PR TITLE
MED3 ccs working

### PR DESCRIPTION
**Pull request by KilveEng**
CCS charging added and other improvements

### CODE REVIEW

**Comment by dexterbg** [comment]
Shane, great feature extension for the Maxus :+1: 

I'd say user documentation is due now… ;-)

For merging, please add an entry to the `changes.txt` file, so users will know what's new.

Thanks,
Michael

**Comment by KilveEng** [comment]
Hi Michael.

Ive add an entry to the changes.txt so that should be good to go,

Ill have another go ad doing user docs, but failed miserably last time


Also any idea why this keeps failing?

https://github.com/MG-EV-Hackers/Open-Vehicle-Monitoring-System-3-MGEV/pull/23 <https://github.com/MG-EV-Hackers/Open-Vehicle-Monitoring-System-3-MGEV/pull/23>

Regards Shane

**Comment by dexterbg** [comment]
Shane, did you delete the branch by accident? The PR is closed as well.

**Comment by KilveEng** [comment]
Oh bugger!

I was advised to re clone the the current master and re do my mods as had loads of commits for the MG

Now ive dont that ive lost my branch and if I add my work to the new clone it won’t compile

So just trying to sort that

Shane

**Comment by KilveEng** [comment]
If you can shed any light im getting this

***@***.*** OVMS.V3 % make
Toolchain path: /Users/shane/.espressif/tools/xtensa-esp32-elf/1.22.0-97-gc752ad5-5.2.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc
Toolchain version: crosstool-ng-1.22.0-97-gc752ad5
Compiler version: 5.2.0
Python requirements from /Users/shane/esp-idf/requirements.txt are satisfied.

App "ovms3" version: 3.3.001-111-ga83d62bd-dirty
LD build/ovms3.elf
/Users/shane/Open-Vehicle-Monitoring-System-3-MGEV/vehicle/OVMS.V3/build/vehicle_mgev/libvehicle_mgev.a(vehicle_mgev_a.o):(.rodata._ZTV16OvmsVehicleMgEvA[vtable for OvmsVehicleMgEvA]+0x174): undefined reference to `OvmsVehicleMgEv::CommandHomelink(int, int)'
/Users/shane/Open-Vehicle-Monitoring-System-3-MGEV/vehicle/OVMS.V3/build/vehicle_mgev/libvehicle_mgev.a(vehicle_mgev_a.o):(.rodata._ZTV16OvmsVehicleMgEvA[vtable for OvmsVehicleMgEvA]+0x1ac): undefined reference to `OvmsVehicleMgEv::calculateEfficiency()'
collect2: error: ld returned 1 exit status
make: *** [/Users/shane/Open-Vehicle-Monitoring-System-3-MGEV/vehicle/OVMS.V3/build/ovms3.elf] Error 1
***@***.*** OVMS.V3 %

**Comment by dexterbg** [comment]
Not sure if I understand your issue correctly. If you've lost the branch locally as well, you should be able to restore the branch on the commit hash. As long as you don't do a gc, the commits are still there.

Not sure though if github cloned the commits for the PR, never had this case. If it didn't clone the commits, you should be able to recreate the branch at 7fef8aefcede0555f78cc6f01139f9948e050ba1.

**Comment by KilveEng** [comment]
Hi Michael, 

I re did a clone from ovms master added my back up of MED3 and did a new pull request 

How ever I have just tried to compile it and just get this now!!

***@***.*** OVMS.V3 % make
Toolchain path: /Users/shane/.espressif/tools/xtensa-esp32-elf/1.22.0-97-gc752ad5-5.2.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc
Toolchain version: crosstool-ng-1.22.0-97-gc752ad5
Compiler version: 5.2.0
Python requirements from /Users/shane/esp-idf/requirements.txt are satisfied.

App "ovms3" version: 3.3.001-112-g57b374dd
CXX build/can/src/canlog.o
In file included from /Users/shane/Open-Vehicle-Monitoring-System-3/vehicle/OVMS.V3/components/ovms_cellular/src/ovms_cellular.h:43:0,
                 from /Users/shane/Open-Vehicle-Monitoring-System-3/vehicle/OVMS.V3/main/ovms_peripherals.h:71,
                 from /Users/shane/Open-Vehicle-Monitoring-System-3/vehicle/OVMS.V3/components/can/src/canlog.cpp:42:
/Users/shane/Open-Vehicle-Monitoring-System-3/vehicle/OVMS.V3/components/ovms_cellular/src/gsmpppos.h:64:5: error: 'ppp_pcb' does not name a type
     ppp_pcb*     m_ppp;
     ^
make[1]: *** [src/canlog.o] Error 1
make: *** [component-can-build] Error 2
***@***.*** OVMS.V3 % 

Thats nothing to do with what ive added?

Shane

**Comment by dexterbg** [comment]
No, that has no connection to your PR. It looks like your esp-idf has the wrong path (env var `IDF_PATH`?), has been damaged or is checked out on the wrong branch.

**Comment by KilveEng** [comment]
Morning Michael, thank you for merging the pull request, 

Seems your right about the esp-idf and I have some investigating to do

Shane

**Comment by KilveEng** [comment]
Evening Michael,

I have got most the problems sorted now 

But have run into this


***@***.*** OVMS.V3 % make
Toolchain path: /Users/shane/esp/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc
Toolchain version: crosstool-ng-1.22.0-97-gc752ad5
Compiler version: 5.2.0
Python requirements from /Users/shane/esp/esp-idf/requirements.txt are satisfied.
make[2]: *** No rule to make target `/Users/shane/esp-idf/components/log/log.c', needed by `log.o'.  Stop.
make[1]: *** [component-log-build] Error 2
make: *** [/Users/shane/Open-Vehicle-Monitoring-System-3-MGEV/vehicle/OVMS.V3/build/bootloader/bootloader.bin] Error 2

The hilighted bit should be /Users/Shane/esp/esp-idf/components/log/log.c

But can’t work out why the esp bit is missing all my tool paths are correct in the .zprofile

Any help appreciated

Shane

**Pull request closed without merging**
