### PR TITLE
convert wolfssl to a git submodule

### PR DESCRIPTION
**Pull request by llange**
wolfssl has been forked (https://github.com/openvehicles/wolfssl) and the subdirectory converted to a Git submodule.
Additionally, it has been put one directory level below (in vehicle/OVMS.V3/components/wolfssl/wolfssl) to better separate the upstream code from our build glue (component.mk, CMakeLists.txt and configuration files)

This way it's easier to track any changes made to the module, upgrade when upstram changes, or propose patches to upstream.

We kept the existing version (v4.7.0-stable) - it will be upgraded later

### CODE REVIEW

**Comment by llange** [comment]
Depends on openvehicles/wolfssl#1 and openvehicles/wolfssl#2 so that we can reference the [tip of the (patched) 4.7.0 branch](https://github.com/openvehicles/wolfssl/tree/v4.7.0-stable-ovms)

**Comment by llange** [comment]
Review and merge is now possible.

**Review by neomilium — APPROVED** [review]

**Comment by neomilium** [comment]
It was easy to review code but hard to know if it works as expected. I rely on @llange 's own build and tests.

**Comment by markwj** [comment]
This seems ok to me. Apart from some parts of it used by wolfssh, we don't seem to use this module at all. So long as ssh connections can still be established to the box, I think this is ok.

**Review by markwj — APPROVED** [review]
This seems ok to me. Apart from some parts of it used by wolfssh, we don't seem to use this module at all. So long as ssh connections can still be established to the box, I think this is ok.

**Pull request merged**
